# Generated by Django 2.2.7 on 2020-08-23 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('rant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmplyeeCategory',
            fields=[
                ('ec_id', models.AutoField(primary_key=True, serialize=False)),
                ('emplyee_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maneeger',
            fields=[
                ('direcotr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelwork.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('cast_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField(default=0)),
                ('email_id', models.EmailField(default=0, max_length=254)),
                ('adhar_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('cheak_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cheak_out_time', models.DateTimeField()),
                ('advance_payment', models.IntegerField(default=0)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelwork.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('emplyee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('salary', models.IntegerField(default=0)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('image', models.ImageField(upload_to='media/')),
                ('address', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelwork.EmplyeeCategory')),
            ],
        ),
    ]
